export type Market = 'es' | 'en'

export const content = {
  es: {
    nav: {
      logo: 'DNAIT STAGE',
      links: ['El Proyecto', 'Programa', 'Precios', 'Equipo', 'Sedes', 'FAQ'],
      cta: 'Inscríbete',
    },
    hero: {
      badge: 'EXPERIENCIA INTERNACIONAL',
      headline: 'Entrena Como Un Campeón',
      subtitle: 'Programa de tenis de élite para jugadores competitivos de 10 a 18 años',
      claim: 'Train. Compete. Experience.',
      fullName: 'International Tennis Experience',
      cta: 'Reserva Tu Plaza',
      ctaSecondary: 'Ver Programa',
      stats: [
        { value: '50', label: 'PLAZAS' },
        { value: '7', label: 'DÍAS' },
        { value: '2', label: 'CIUDADES' },
      ],
    },
    about: {
      badge: 'El Proyecto',
      title: '¿Qué es DNAIT STAGE?',
      description: 'El primer stage internacional de tenis que fusiona dos academias de dos continentes: Tennis DNA (Virginia, EE.UU.) y AIT Tenis (Madrid, España). 50 jugadores junior de 10 a 18 años vivirán una semana de entrenamiento intensivo, actividades de aventura y una experiencia cultural única entre Madrid y Valencia.',
      secondary: 'DNAIT nace de la fusión de DNA + AIT: dos organizaciones, un mismo objetivo. Suena como "dynamite" en inglés — energía explosiva, impacto inmediato. Una semana que cambiará tu juego para siempre.',
      features: [
        { icon: 'tennis', title: 'Entrenamiento de élite', text: 'Coaches USPTA/PTR americanos + entrenadores profesionales españoles. Ratio máximo 6:1 por pista. Metodología combinada de dos escuelas.' },
        { icon: 'flag', title: 'Entrenamiento de alto nivel', text: 'Entrena con la metodología que ha producido campeones como Nadal, Alcaraz y Ferrer. Mejor técnica, mejor juego de piernas, mejor competitividad.' },
        { icon: 'building', title: 'Sede histórica', text: 'Real Centro Universitario Escorial María Cristina. 100 habitaciones con baño, pensión completa, seguridad 24/7, wifi gratuito. A 45 minutos de Madrid.' },
        { icon: 'globe', title: 'Dos países, una marca', text: 'Co-branding 50/50 entre Tennis DNA y AIT Tenis. Intercambio deportivo real entre jugadores americanos y españoles. No es un campus más — es tu Stage internacional.' },
      ],
      marketingAngle: 'Tu hijo entrenará con jugadores americanos de alto nivel en una experiencia internacional única.',
    },
    schedule: {
      badge: 'El Programa',
      title: '7 Días Que Cambiarán Tu Juego',
      subtitle: 'De Madrid a Valencia: entrenamiento intensivo, aventura y cultura en una semana inolvidable.',
      days: [
        { day: 1, date: 'Dom 20 Jul', title: 'Llegada y Bienvenida', location: 'Madrid', type: 'arrival', highlights: ['Recogida en aeropuerto Madrid-Barajas', 'Traslado al RCU Escorial María Cristina', 'Cena ligera y reunión de bienvenida'] },
        { day: 2, date: 'Lun 21 Jul', title: 'Primera Sesión + Tirolinas', location: 'El Escorial', type: 'training', highlights: ['Sesión de tenis: técnica individual', 'Preparación física', 'Tirolinas en Aventura Amazonia (Cercedilla)'] },
        { day: 3, date: 'Mar 22 Jul', title: 'Defensa y Consistencia + Paintball', location: 'El Escorial', type: 'training', highlights: ['Tenis: consistencia y defensa', 'Preparación física: resistencia', 'Paintball por equipos'] },
        { day: 4, date: 'Mié 23 Jul', title: 'Intensidad Máxima + Madrid', location: 'El Escorial + Madrid', type: 'adventure', highlights: ['Drills de intensidad y partidos', 'Preparación física: potencia', 'Visita cultural a Madrid + cena'] },
        { day: 5, date: 'Jue 24 Jul', title: 'Tenis Técnico + Aquópolis', location: 'El Escorial', type: 'adventure', highlights: ['Entrenamiento técnico ligero', 'Aquópolis — parque acuático', 'Tarde de relax y diversión'] },
        { day: 6, date: 'Vie 25 Jul', title: 'Valencia — Entrenamiento + Partidos', location: 'Valencia', type: 'training', highlights: ['Salida hacia Valencia', 'Entrenamiento en Gtennis Academy', 'Partidos vs jugadores locales'] },
        { day: 7, date: 'Sáb 26 Jul', title: 'Mini Torneo USA vs España + Despedida', location: 'Valencia', type: 'competition', highlights: ['Entrenamiento conjunto', 'Mini torneo USA vs España', 'Ciudad de las Artes + cena de despedida'] },
        { day: 8, date: 'Dom 27 Jul', title: 'Playa y Regreso', location: 'Valencia', type: 'departure', highlights: ['Mañana de playa', 'Comida', 'Traslado al aeropuerto de Valencia'] },
      ],
    },
    pricing: {
      badge: 'Packs y Precios',
      title: '3 Opciones de Inscripción',
      subtitle: 'Elige la experiencia que mejor se adapte a tus necesidades. Todos los packs incluyen entrenamiento con coaches internacionales.',
      currency: '€',
      packs: [
        {
          name: 'Pack Externo',
          tag: '',
          description: 'Solo entrenamiento',
          price: '895',
          period: '5 días',
          features: ['5 días de entrenamiento intensivo', 'Almuerzo incluido', 'Actividades complementarias (sin pernocta)', 'Kit de bienvenida (camiseta)', 'Seguro deportivo'],
          cta: 'Más Info',
          recommended: false,
        },
        {
          name: 'Pack Completo',
          tag: 'RECOMENDADO',
          description: '7 días · Madrid + Valencia',
          price: '1.300',
          period: 'Todo incluido',
          features: ['Alojamiento RCU Escorial (pensión completa)', '5 días de entrenamiento intensivo (ratio 6:1)', 'Actividades de aventura (tirolinas, paintball, Aquópolis)', 'Visita cultural a Madrid', 'Traslado y estancia en Valencia', 'Entrenamiento y partidos en Gtennis Academy', 'Ciudad de las Artes y las Ciencias', 'Mañana de playa', 'Cena de despedida + diplomas', 'Kit completo + seguro + video resumen'],
          cta: 'Inscribirse Ahora',
          recommended: true,
        },
        {
          name: 'Pack Madrid',
          tag: '',
          description: '5 días / 4 noches',
          price: '950',
          period: 'Solo Madrid',
          features: ['Alojamiento RCU Escorial (pensión completa)', '5 días de entrenamiento intensivo', 'Actividades complementarias', 'Visita cultural a Madrid', 'Kit de bienvenida', 'Seguro deportivo'],
          cta: 'Más Info',
          recommended: false,
        },
      ],
      extras: [
        { name: 'Transfer aeropuerto Madrid-Barajas (ida y vuelta)', price: '150' },
        { name: 'Pack de fotos profesional individual', price: '75' },
        { name: 'Clase privada adicional (1h con coach)', price: '120' },
        { name: 'Acompañante/familiar (alojamiento + comidas)', price: '800' },
      ],
      discounts: [
        { name: 'Early Bird', condition: 'Inscripción antes del 30 de abril', percent: '-10%' },
        { name: 'Hermanos', condition: '2 o más hermanos inscritos', percent: '-15% al 2º' },
        { name: 'Grupo', condition: '4+ jugadores del mismo club', percent: '-10%' },
        { name: 'Alumni', condition: 'Alumnos de Tennis DNA o AIT Tenis', percent: '-5%' },
      ],
      discountNote: 'Los descuentos no son acumulables. Contacta con nosotros para consultar tu caso.',
    },
    coaches: {
      badge: 'El Equipo',
      title: 'Coaches de Dos Continentes',
      subtitle: 'Un equipo internacional de entrenadores certificados que combinan la metodología americana con la tradición del tenis español.',
      ratio: 'Ratio máximo 6:1 (6 jugadores por coach). Metodología que combina la intensidad del entrenamiento americano (USPTA/PTR) con la técnica y tradición del tenis español.',
      teams: [
        {
          name: 'Tennis DNA (EE.UU.)',
          members: [
            { name: 'Sean Moran', role: 'CEO & Fundador', bio: 'Más de 15 años desarrollando tenis junior en Virginia y Maryland. Filosofía: formar jugadores completos dentro y fuera de la pista.' },
            { name: 'Pedro Avia', role: 'Director de Operaciones', bio: 'Coordina todas las operaciones deportivas. Enlace entre el equipo americano y español. Contacto directo del Stage.' },
            { name: 'Endre Esztergomi', role: 'Head Coach', bio: 'Entrenador principal con formación internacional. Especialista en desarrollo técnico y táctico de jugadores competitivos.' },
            { name: 'Juan Durán', role: 'Director de Tenis', bio: 'Amplia experiencia en formación de jugadores junior de alto rendimiento. Diseño metodológico de las sesiones.' },
          ],
        },
        {
          name: 'AIT Tenis (España)',
          members: [
            { name: 'Ignacio', role: 'Director & Entrenador principal', bio: 'Director de AIT Tenis con años de experiencia en tenis de competición. Co-director del Stage y responsable de operaciones en España.' },
            { name: 'Alex', role: 'Entrenador & Co-director', bio: 'Especialista en preparación física aplicada al tenis. Coordina actividades complementarias y logística local.' },
          ],
        },
      ],
    },
    venues: {
      badge: 'Las Sedes',
      title: 'Madrid + Valencia',
      subtitle: 'Dos ciudades, dos experiencias. Del entrenamiento intensivo en la Sierra de Guadarrama a los partidos internacionales en la costa mediterránea.',
      locations: [
        {
          name: 'RCU Escorial María Cristina',
          city: 'Madrid',
          description: 'Residencia universitaria histórica junto al Monasterio de El Escorial, Patrimonio de la Humanidad. Tradición y modernidad a 45 min de Madrid.',
          features: ['100 habitaciones con baño', 'Pensión completa', 'Wifi gratuito', 'Seguridad 24/7', '8 pistas de tenis', 'Pabellón deportivo'],
        },
        {
          name: 'Gtennis Academy',
          city: 'Valencia',
          description: 'Academia de referencia en la Comunidad Valenciana. Instalaciones de primer nivel para el tramo final del Stage.',
          features: ['6 pistas de tenis', 'Instalaciones profesionales', 'Zona de playa cercana', 'Ciudad de las Artes'],
        },
      ],
    },
    faq: {
      badge: 'FAQ',
      title: 'Preguntas Frecuentes',
      subtitle: 'Todo lo que necesitas saber sobre DNAIT STAGE.',
      items: [
        { q: '¿Qué es DNAIT STAGE?', a: 'El primer stage internacional de tenis que fusiona Tennis DNA (Virginia, EE.UU.) y AIT Tenis (Madrid, España). 50 jugadores junior de 10-18 años en una semana de entrenamiento, aventura y cultura entre Madrid y Valencia.' },
        { q: '¿Cuándo se celebra?', a: 'Del 20 al 27 de julio de 2026 (7 días / 6 noches para el Pack Completo).' },
        { q: '¿Qué nivel se necesita?', a: 'Jugadores competitivos de nivel intermedio a avanzado. No es necesario estar federado, pero sí tener experiencia en competición.' },
        { q: '¿En qué idioma se entrena?', a: 'En inglés y español. Todos los coaches son bilingües o se apoyan mutuamente.' },
        { q: '¿Dónde se alojan los jugadores?', a: 'En el RCU Escorial María Cristina. Habitaciones con baño, pensión completa, wifi, seguridad 24/7.' },
        { q: '¿Es seguro?', a: 'Sí. Recepción 24h, supervisión permanente, seguro deportivo incluido, hospital a 5 minutos.' },
        { q: '¿Están incluidos los vuelos?', a: 'No. Llegada a Madrid-Barajas, salida desde Valencia. Transfer disponible por 150€.' },
        { q: '¿Se puede asistir solo a Madrid?', a: 'Sí. El Pack Madrid incluye 5 días / 4 noches solo en El Escorial.' },
        { q: '¿Hay descuentos?', a: 'Sí: Early Bird -10% (antes del 30 de abril), hermanos -15% al 2º, grupo 4+ jugadores -10%, alumni -5%.' },
        { q: '¿Cómo se paga?', a: 'Depósito del 30% para confirmar plaza, resto antes del 15 de junio. Transferencia o tarjeta.' },
      ],
    },
    form: {
      badge: 'Inscripción',
      title: 'Inscripción DNAIT STAGE 2026',
      subtitle: 'Completa el formulario y nos pondremos en contacto contigo en menos de 24 horas.',
      fields: {
        name: 'Nombre completo del jugador',
        email: 'Email',
        phone: 'Teléfono (con prefijo)',
        age: 'Edad del jugador',
        country: 'País de residencia',
        level: 'Nivel de tenis',
        pack: 'Pack seleccionado',
        source: '¿Cómo nos conociste?',
        allergies: 'Alergias o medicación',
        message: 'Comentarios adicionales',
      },
      levels: ['Principiante', 'Intermedio', 'Avanzado', 'Competición'],
      sources: ['Instagram', 'Facebook', 'Email', 'Amigo/Conocido', 'Club de tenis', 'Google', 'Otro'],
      countries: ['España', 'Estados Unidos', 'Otro'],
      submit: 'Enviar Inscripción',
      successTitle: '¡Inscripción enviada!',
      successText: 'Recibirás un email de confirmación en las próximas 24 horas.',
      note: 'Al enviar este formulario, recibirás un email de confirmación con toda la información y las instrucciones de pago.',
    },
    cta: {
      claim: 'Train. Compete. Experience.',
      title: 'Solo 50 plazas disponibles',
      subtitle: 'Esta es tu oportunidad de vivir una experiencia internacional única.',
      button: 'Reserva Tu Plaza Ahora',
    },
    footer: {
      tagline: 'International Tennis Experience',
      date: 'Julio 2026 · Madrid + Valencia',
      tdna: { name: 'Tennis DNA', url: 'https://tennis-dna.com', location: 'Virginia, EE.UU.' },
      ait: { name: 'AIT Tenis', url: 'https://aittenis.es', location: 'Madrid, España' },
      contact: { email: 'pedro@tennis-dna.com', ig1: '@tennis.dna.coaching', ig2: '@aittenis' },
      copy: '© 2026 DNAIT STAGE · Tennis DNA × AIT Tenis · Todos los derechos reservados',
    },
  },
  en: {
    nav: {
      logo: 'DNAIT STAGE',
      links: ['The Project', 'Schedule', 'Pricing', 'Coaches', 'Venues', 'FAQ'],
      cta: 'Register',
    },
    hero: {
      badge: 'INTERNATIONAL EXPERIENCE',
      headline: 'Train Like A Champion',
      subtitle: 'Elite tennis program for competitive players aged 10 to 18',
      claim: 'Train. Compete. Experience.',
      fullName: 'International Tennis Experience',
      cta: 'Reserve Your Spot',
      ctaSecondary: 'View Schedule',
      stats: [
        { value: '50', label: 'SPOTS' },
        { value: '7', label: 'DAYS' },
        { value: '2', label: 'COUNTRIES' },
      ],
    },
    about: {
      badge: 'The Project',
      title: 'What is DNAIT STAGE?',
      description: 'The first international tennis stage bringing together two academies from two continents: Tennis DNA (Virginia, USA) and AIT Tenis (Madrid, Spain). 50 junior players aged 10 to 18 will experience a week of intensive tennis training, adventure activities, and a unique cultural immersion between Madrid and Valencia.',
      secondary: 'DNAIT is the fusion of DNA + AIT: two organizations, one shared goal. It sounds like "dynamite" — explosive energy, instant impact. One week that will change your game forever.',
      features: [
        { icon: 'tennis', title: 'Elite Coaching', text: 'USPTA/PTR certified American coaches + Spanish professional trainers. Maximum 6:1 player-to-coach ratio. Combined methodology from two world-class schools.' },
        { icon: 'flag', title: 'Elite Training', text: 'Train with the methodology that produced champions like Nadal, Alcaraz, and Ferrer. Better technique, better footwork, better competitive edge.' },
        { icon: 'building', title: 'Historic Venue', text: 'Real Centro Universitario Escorial María Cristina. 100 rooms with private bathrooms, full board, 24/7 security, free wifi. 45 min from Madrid.' },
        { icon: 'globe', title: 'Two Countries, One Brand', text: '50/50 co-branding between Tennis DNA and AIT Tenis. Real competitive exchange between American and Spanish players. Not just another camp — it\'s your International Stage.' },
      ],
      marketingAngle: 'Give your child the ultimate international tennis experience in Spain.',
    },
    schedule: {
      badge: 'The Schedule',
      title: '7 Days That Will Change Your Game',
      subtitle: 'From Madrid to Valencia: intensive training, adventure, and culture in one unforgettable week.',
      days: [
        { day: 1, date: 'Sun Jul 20', title: 'Arrival & Welcome', location: 'Madrid', type: 'arrival', highlights: ['Airport pickup at Madrid-Barajas', 'Transfer to RCU Escorial María Cristina', 'Light dinner and welcome meeting'] },
        { day: 2, date: 'Mon Jul 21', title: 'First Session + Zip Lines', location: 'El Escorial', type: 'training', highlights: ['Tennis: individual technique', 'Physical conditioning', 'Zip lines at Aventura Amazonia (mountains)'] },
        { day: 3, date: 'Tue Jul 22', title: 'Defense & Consistency + Paintball', location: 'El Escorial', type: 'training', highlights: ['Tennis: consistency and defense', 'Physical conditioning: endurance', 'Team paintball'] },
        { day: 4, date: 'Wed Jul 23', title: 'Maximum Intensity + Madrid Tour', location: 'El Escorial + Madrid', type: 'adventure', highlights: ['Intensity drills and match play', 'Physical conditioning: power', 'Madrid city tour + dinner'] },
        { day: 5, date: 'Thu Jul 24', title: 'Technical Tennis + Water Park', location: 'El Escorial', type: 'adventure', highlights: ['Light technical training', 'Aquópolis water park', 'Relaxation and fun'] },
        { day: 6, date: 'Fri Jul 25', title: 'Valencia — Training + Matches', location: 'Valencia', type: 'training', highlights: ['Travel to Valencia', 'Training at Gtennis Academy', 'Matches vs local players'] },
        { day: 7, date: 'Sat Jul 26', title: 'USA vs Spain Mini Tournament + Farewell', location: 'Valencia', type: 'competition', highlights: ['Joint training session', 'USA vs Spain mini tournament', 'City of Arts + farewell dinner'] },
        { day: 8, date: 'Sun Jul 27', title: 'Beach & Departure', location: 'Valencia', type: 'departure', highlights: ['Beach morning', 'Lunch', 'Transfer to Valencia Airport'] },
      ],
    },
    pricing: {
      badge: 'Packs & Pricing',
      title: '3 Registration Options',
      subtitle: 'Choose the experience that best fits your needs. All packs include training with international coaches.',
      currency: '$',
      packs: [
        {
          name: 'External Pack',
          tag: '',
          description: 'Training only',
          price: '895',
          period: '5 days',
          features: ['5 days of intensive training', 'Lunch included', 'Complementary activities (no overnight)', 'Welcome kit (t-shirt)', 'Sports insurance'],
          cta: 'More Info',
          recommended: false,
        },
        {
          name: 'Full Pack',
          tag: 'RECOMMENDED',
          description: '7 days · Madrid + Valencia',
          price: '2,495',
          period: 'All-inclusive',
          features: ['Accommodation at RCU Escorial (full board)', '5 days intensive training (6:1 ratio)', 'Adventure activities (zip lines, paintball, water park)', 'Madrid city tour', 'Transfer and stay in Valencia', 'Training and matches at Gtennis Academy', 'City of Arts and Sciences', 'Beach morning', 'Farewell dinner + diplomas', 'Full kit + insurance + highlight video'],
          cta: 'Register Now',
          recommended: true,
        },
        {
          name: 'Madrid Pack',
          tag: '',
          description: '5 days / 4 nights',
          price: '1,895',
          period: 'Madrid only',
          features: ['Accommodation at RCU Escorial (full board)', '5 days of intensive training', 'Complementary activities', 'Madrid city tour', 'Welcome kit', 'Sports insurance'],
          cta: 'More Info',
          recommended: false,
        },
      ],
      extras: [
        { name: 'Airport transfer Madrid-Barajas (round trip)', price: '150' },
        { name: 'Professional individual photo package', price: '75' },
        { name: 'Private lesson (1h with coach)', price: '120' },
        { name: 'Companion/family member (accommodation + meals)', price: '800' },
      ],
      discounts: [
        { name: 'Early Bird', condition: 'Register before April 30', percent: '-10%' },
        { name: 'Siblings', condition: '2 or more siblings enrolled', percent: '-15% on 2nd' },
        { name: 'Group', condition: '4+ players from same club', percent: '-10%' },
        { name: 'Alumni', condition: 'Tennis DNA or AIT Tenis students', percent: '-5%' },
      ],
      discountNote: 'Discounts cannot be combined. Contact us to discuss your situation.',
    },
    coaches: {
      badge: 'The Team',
      title: 'Coaches From Two Continents',
      subtitle: 'An international team of certified coaches combining American methodology with the Spanish tennis tradition.',
      ratio: 'Maximum 6:1 ratio (6 players per coach). A methodology combining the intensity of American training (USPTA/PTR) with the technique and tradition of Spanish tennis.',
      teams: [
        {
          name: 'Tennis DNA (USA)',
          members: [
            { name: 'Sean Moran', role: 'CEO & Founder', bio: 'Over 15 years developing junior tennis in Virginia and Maryland. Philosophy: develop complete players on and off the court.' },
            { name: 'Pedro Avia', role: 'Director of Operations', bio: 'Coordinates all tennis operations. Direct liaison between American and Spanish teams. Stage point of contact.' },
            { name: 'Endre Esztergomi', role: 'Head Coach', bio: 'Head coach with international training background. Specialist in technical and tactical development of competitive players.' },
            { name: 'Juan Durán', role: 'Tennis Director', bio: 'Extensive experience in high-performance junior development. Methodological design of Stage training sessions.' },
          ],
        },
        {
          name: 'AIT Tenis (Spain)',
          members: [
            { name: 'Ignacio', role: 'Director & Head Coach', bio: 'Director of AIT Tenis with years of competitive tennis experience. Stage co-director and responsible for operations in Spain.' },
            { name: 'Alex', role: 'Coach & Co-director', bio: 'Specialist in tennis-specific physical preparation. Coordinates complementary activities and local logistics.' },
          ],
        },
      ],
    },
    venues: {
      badge: 'The Venues',
      title: 'Madrid + Valencia',
      subtitle: 'Two cities, two experiences. From intensive training in the Sierra de Guadarrama mountains to international matches on the Mediterranean coast.',
      locations: [
        {
          name: 'RCU Escorial María Cristina',
          city: 'Madrid',
          description: 'Historic university residence next to El Escorial Monastery, a UNESCO World Heritage Site. Tradition and modernity, 45 min from Madrid.',
          features: ['100 rooms with bathrooms', 'Full board', 'Free wifi', '24/7 security', '8 tennis courts', 'Sports pavilion'],
        },
        {
          name: 'Gtennis Academy',
          city: 'Valencia',
          description: 'Leading tennis academy in the Valencia region. First-class facilities for the final stretch of the Stage.',
          features: ['6 tennis courts', 'Professional facilities', 'Nearby beach area', 'City of Arts and Sciences'],
        },
      ],
    },
    faq: {
      badge: 'FAQ',
      title: 'Frequently Asked Questions',
      subtitle: 'Everything you need to know about DNAIT STAGE.',
      items: [
        { q: 'What is DNAIT STAGE?', a: 'The first international tennis stage by Tennis DNA (Virginia, USA) and AIT Tenis (Madrid, Spain). 50 junior players aged 10-18 in a week of training, adventure, and culture across Madrid and Valencia.' },
        { q: 'When does it take place?', a: 'July 20-27, 2026 (7 days / 6 nights for the Full Pack).' },
        { q: 'What level is required?', a: 'Competitive intermediate to advanced players. Federation membership not required, but competition experience is expected.' },
        { q: 'What language are sessions in?', a: 'English and Spanish. All coaches are bilingual or support each other so every player understands.' },
        { q: 'Where do players stay?', a: 'At RCU Escorial María Cristina. Rooms with private bathrooms, full board, wifi, 24/7 security.' },
        { q: 'Is it safe?', a: 'Yes. 24h reception, permanent supervision, sports insurance included, hospital 5 minutes away.' },
        { q: 'Are flights included?', a: 'No. Arrive at Madrid-Barajas, depart from Valencia. Airport transfer available for $150.' },
        { q: 'Can I attend just the Madrid portion?', a: 'Yes. The Madrid Pack includes 5 days / 4 nights at El Escorial only.' },
        { q: 'Are there discounts?', a: 'Yes: Early Bird -10% (before April 30), siblings -15% on 2nd, group 4+ players -10%, alumni -5%.' },
        { q: 'How does payment work?', a: '30% deposit to confirm your spot, remainder due before June 15. Bank transfer or card.' },
      ],
    },
    form: {
      badge: 'Registration',
      title: 'DNAIT STAGE 2026 Registration',
      subtitle: 'Fill out the form and we\'ll get back to you within 24 hours.',
      fields: {
        name: 'Player\'s full name',
        email: 'Email',
        phone: 'Phone (with country code)',
        age: 'Player\'s age',
        country: 'Country of residence',
        level: 'Tennis level',
        pack: 'Selected pack',
        source: 'How did you hear about us?',
        allergies: 'Allergies or medication',
        message: 'Additional comments',
      },
      levels: ['Beginner', 'Intermediate', 'Advanced', 'Competition'],
      sources: ['Instagram', 'Facebook', 'Email', 'Friend/Referral', 'Tennis club', 'Google', 'Other'],
      countries: ['United States', 'Spain', 'Other'],
      submit: 'Submit Registration',
      successTitle: 'Registration submitted!',
      successText: 'You\'ll receive a confirmation email within 24 hours.',
      note: 'Upon submission, you\'ll receive a confirmation email with all Stage details and payment instructions.',
    },
    cta: {
      claim: 'Train. Compete. Experience.',
      title: 'Only 50 spots available',
      subtitle: 'This is your chance to live a one-of-a-kind international tennis experience.',
      button: 'Reserve Your Spot Now',
    },
    footer: {
      tagline: 'International Tennis Experience',
      date: 'July 2026 · Madrid + Valencia',
      tdna: { name: 'Tennis DNA', url: 'https://tennis-dna.com', location: 'Virginia, USA' },
      ait: { name: 'AIT Tenis', url: 'https://aittenis.es', location: 'Madrid, Spain' },
      contact: { email: 'pedro@tennis-dna.com', ig1: '@tennis.dna.coaching', ig2: '@aittenis' },
      copy: '© 2026 DNAIT STAGE · Tennis DNA × AIT Tenis · All rights reserved',
    },
  },
}
